language: bash

sudo: false

git:
    depth: 200

env:
    global:
        - PATH=$PATH:$HOME/bin

    matrix:
        - ARCH=x86_64
        - ARCH=i686
        - ARCH=armv6hf
        - ARCH=armv7hf
cache:
      directories:
              - $HOME/hostdir/repocache
before_cache:
    - mv hostdir/repocache/* $HOME/repocache

before_script:
    - common/travis/prepare.sh
    - common/travis/fetch_upstream.sh
    - common/travis/changed_templates.sh
    - common/travis/xlint.sh
    - common/travis/bootstrap.sh

script:
    - common/travis/build.sh $ARCH

after_script:
    - common/travis/show_files.sh

notifications:
    email: false
