language: bash

git:
    depth: 200

env:
    global:
        - PATH=$PATH:$PWD/xtools

before_script:
    - git clone --depth 1 git://github.com/chneukirchen/xtools.git xtools

script:
    - git fetch --depth 1 git://github.com/voidlinux/void-packages.git master
    - git diff --name-status FETCH_HEAD...HEAD | grep "^[AM].*srcpkgs/[^/]*/template$" | awk '{print $2}' | tee __changed_templates
    - xlint `cat __changed_templates`

notifications:
    email: false
