language: bash

git:
    depth: 200

env:
    global:
        - PATH=$PATH:$PWD/xtools

before_script:
    - git clone --depth 1 git://github.com/chneukirchen/xtools.git xtools

script:
    - git remote add upstream git://github.com/voidlinux/void-packages.git
    - git fetch --depth 1 upstream master
    - git diff --name-status upstream/master > __changed_files
    - grep "^[AM].*srcpkgs/[^/]*/template$" __changed_files | awk '{print $2}' | tee __changed_templates
    - xlint `cat __changed_templates`

notifications:
    email: false
