language: bash

git:
    depth: 200

env:
    global:
        - PATH=$PATH:$PWD/xtools

before_script:
    - git clone git://github.com/chneukirchen/xtools.git xtools

script:
    - echo "Checking: $TRAVIS_COMMIT_RANGE"
    - git diff --name-status -- "$TRAVIS_COMMIT_RANGE" > __changed_files
    - cat __changed_files
    - grep "^[AM].*srcpkgs/[^/]*/template$" __changed_files | awk '{print $2}' | tee __changed_templates
    - xlint `cat __changed_templates`

notifications:
    email: false
