language: bash

git:
    depth: 200

env:
    global:
        - PATH=$PATH:$PWD/xtools

before_script:
    - git clone --depth 1 git://github.com/chneukirchen/xtools.git xtools

script:
    - git remote add __upstream git://github.com/voidlinux/void-packages.git; git fetch --depth 200 __upstream master
    - git diff --name-status `git merge-base __upstream/master HEAD` | grep "^[AM].*srcpkgs/[^/]*/template$" | awk '{print $2}' | tee __changed_templates
    - xlint `cat __changed_templates`

notifications:
    email: false
