name: "Push Notification"
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened, closed]

jobs:
  ircnotify:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push' && github.repository == 'void-linux/void-packages'
        with:
          notice: true
          channel: "#xbps"
          nickname: void-packages
          tls: true
          message: |
            ${{ github.actor }} pushed ${{ github.event.compare }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request' && github.repository == 'void-linux/void-packages'
        with:
          notice: true
          channel: "#xbps"
          nickname: void-packages
          tls: true
          message: |
            ${{ github.actor }} ${{ github.event.action }} pull request #${{ github.event.pull_request.html_url }}“ ${{ github.event.pull_request.number }}” 
      - name: irc issue
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'issues' && github.repository == 'void-linux/void-packages'
        with:
          notice: true
          channel: "#xbps"
          nickname: void-packages
          tls: true
          message: |
            ${{ github.actor }} ${{ github.event.action }} issue #${{ github.event.issue.number }} “${{ github.event.issue.html_url }}”
